# https://github.com/kubernetes/ingress-nginx
# helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
# helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx -n infra -f ingress-nginx-values.yaml

controller:
  ingressClassResource:
    default: true

  replicaCount: 1

  resources:
    requests:
      cpu: 100m
      memory: 150Mi

  #podAnnotations:
  #  prometheus.io/scrape: "true"
  #  prometheus.io/port: "10254"

  tolerations:
  - operator: Exists

  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - ingress-nginx
        topologyKey: kubernetes.io/hostname

  service:
    externalTrafficPolicy: Local
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
      service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-xxx,subnet-xxx"
    internal:
      enabled: true
      externalTrafficPolicy: Local
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
        service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
        service.beta.kubernetes.io/aws-load-balancer-internal: "true"
        service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-xxx,subnet-xxx"

imagePullSecrets:
- name: harbor-secret
